#!/usr/bin/env sh

echo "🛠️ Running Linter..."

pnpm lint

if [ $? -ne 0 ]; then
  echo "❌ Lint errors detected. Commit aborted."
  exit 1
fi

echo "✅ Lint passed."

echo "Add the changes..."

git add .

echo "✅ Git added. Proceeding with commit"