name: Continuous Integration

on:
  pull_request:
    branches: [ develop, release, main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    permissions:  # ✅ Required for commenting in private repos
      pull-requests: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "20"

    - name: Cache pnpm store
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Validate PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "PR Title: $PR_TITLE"
        if [[ ! "$PR_TITLE" =~ ^JC-(DEV|PROD)-[A-Za-z0-9\.]+:\ .+ ]]; then
          echo "❌ PR title must follow format: JC-{DEV|PROD}-XXX: MESSAGE"
          exit 1
        fi
        echo "✅ PR title format is valid"
        
    - name: Extract version from PR title
      id: extract_version
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ "$PR_TITLE" =~ ^JC-([A-Z0-9\.]+): ]]; then
          ENV="${BASH_REMATCH[1]}"
          VERSION="${BASH_REMATCH[2]}"
          echo "environment=$ENV" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Environment: $ENV"
          echo "Version: $VERSION"
        fi
        
    - name: Validate CHANGELOG.md
      run: |
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        if ! grep -q "# $PACKAGE_VERSION" CHANGELOG.md; then
          echo "❌ package.json version ($PACKAGE_VERSION) not found in CHANGELOG.md"
          exit 1
        fi
        echo "✅ package.json version matches entry in CHANGELOG.md"
        
    - name: Run linting
      run: pnpm run lint
      
    - name: Type checking
      run: npx tsc --noEmit
      
    - name: Build project
      run: pnpm run build:dev
      env:
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        
    - name: Check build size
      run: |
        BUILD_SIZE=$(du -sh build/dev | cut -f1)
        echo "Build size: $BUILD_SIZE"
        
    - name: Comment PR with build info
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          const buildSize = execSync('du -sh build/dev').toString().split('\t')[0];
    
          const comment = `## 🔍 CI Results
    
          ✅ **PR Title Format**: Valid  
          ✅ **Linting**: Passed  
          ✅ **Type Checking**: Passed  
          ✅ **Build**: Successful  
          📦 **Build Size**: ${buildSize}
    
          **Environment**: ${{ steps.extract_version.outputs.environment }}  
          **Version**: ${{ steps.extract_version.outputs.version }}
          `;
    
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
